# Generated by Django 5.2.6 on 2026-03-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='soil_images/')),
                ('soil_type', models.CharField(max_length=50)),
                ('ph_value', models.FloatField()),
                ('moisture', models.CharField(max_length=20)),
                ('crop', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
