# Generated by Django 5.2.6 on 2026-03-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilscan',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
